### ISSUE TITLE
allow creation of business objects

### ISSUE THREAD

**Issue by sdementen** [sdementen/piecash#1]
Currently, business objects (customer, company, ...) can only be read from a gnucash document but not created.
Adding this ability requires to a) implement proper __init__ and b) use counter stored in slots at book level

**Comment by dgrabla** [comment]
+1

**Comment by sdementen** [comment]
What are the business objects that must be supported in priority ? customer and vendor ? taxtable ?

**Comment by dgrabla** [comment]
customer/vendor will be useful for me

**Comment by sdementen** [comment]
Support to create a Customer is available in the git branch feature/business_objects (see Tutorial on creating new objects on RTD).

**Comment by sdementen** [comment]
Doc link : http://piecash.readthedocs.org/en/feature-business_objects/tutorial/index_new.html#creating-new-business-objects

**Comment by sdementen** [comment]
Release 0.8.2 includes functionnalities to create the following business objects: customer, vendor, employee, tax table with tax table entries. Any feedback is appreciated.

**Comment by dgrabla** [comment]
Thanks!

**Comment by sdementen** [comment]
hello David, if you were to try piecash, start by doing it on copies of
your data and test to see if it works as expected (I haven't used the
business features of gnucash so I am not that familiat with them)
kr
seb
