### ISSUE TITLE
Error in Termux due to PyTZ/tzlocal issue

### ISSUE THREAD

**Issue by MisterY** [sdementen/piecash#101]
As a result of https://github.com/regebro/tzlocal/pull/55, piecash fails in Termux on Android.

This is a recent development (I mean it worked in the past) so it could be a result of Python 3.7 upgrade on Termux.

In any case, just referencing it here since it might be a while until the fix in tzlocal is released. Wondering if the use of pytz is necessary in piecash library.

**Comment by MisterY** [comment]
After inspecting the code, I see that tz is only used when fetching the quotes. Would it be possible to extract this functionality into a separate package?

**Comment by sdementen** [comment]
Re the issue on Termux, you already did what is described in https://piecash.readthedocs.io/en/master/android.html ?

**Comment by MisterY** [comment]
Ah, thanks so much for the reminder! Yes, that's it. Had it before but forgot after the reinstallation. 
Will later link those instructions to the tz issue. It can be used as a workaround until the Android support is released. It is interesting that they don't already know about it.

**Comment by MisterY** [comment]
Well, did not get far, unfortunately. While this resolves the problem when running Termux terminal, there is another issue. I'm running the script through Termux Widget (or Shortcuts?) and that does not seem to use bash_profile for whatever reason. Pending further investigation from my side.

**Comment by MisterY** [comment]
Simple enough, adding those lines to the actual script in ~/.shortcuts directory works.

**Comment by sdementen** [comment]
I think you may also do a `os.environ["TZ"]=...` within your python code at the start of your program (but I haven't tried).
Out of curiosity, what are you building on Android? A flask/django based web app?

**Comment by MisterY** [comment]
Yep 😃. Narrowing down a multiplatform solution to a Progressive Web Application. Now experimenting to see if I should simply run the server on the device or sync when online. I have a few ideas/needs for apps but need to identity a platform that will cover all the devices I use, a lot of code reuse, and be easy to work with. I'll be using GnuCash Portfolio WebUI project for the first real implementation. 
So far I've literally tried out all available Python and mobile GUI options and the above is the only one that ticks all marks. I'd be happy to hear about your experiences!

**Comment by sdementen** [comment]
Have you tried dash by the plotly team?
I guess you can run dash(flask based) on termux

**Comment by MisterY** [comment]
That looks interesting. Will have to try it out at some point when I'm done with deciding about the server-side. Thanks for the pointer. Been very busy with music lately so hardly any time left for development outside work.
