### ISSUE TITLE
Error exporting Unicode char(s) to a file on Windows

### ISSUE THREAD

**Issue by MisterY** [sdementen/piecash#107]
Trying to export the book results in a Unicode error in a Windows terminal. 
`piecash ledger "sql.gnucash" --output export.ledger`

According to docs, Python 3.6 outputs Unicode to the console. That part I can confirm working, as it spits out the content to the console when "--output" parameter is not used. 
The error also happens if redirection ">" is used.

Any ideas? Thanks!

![image](https://user-images.githubusercontent.com/462445/56203493-a5ab7d00-6045-11e9-8921-2af4f777b981.png)

I have piecash 1.0.0 installed from pip.
Python 3.7.3
GnuCash book from v3.5.

**Comment by sdementen** [comment]
Can you try adding a encoding="utf-8" parameter to the click.File call in https://github.com/sdementen/piecash/blob/520024e39451679628b8d663ca90b5f56f1103b7/piecash/scripts/ledger.py#L21 ?

**Comment by MisterY** [comment]
Thanks, I'll try that tomorrow.
On Linux, the command completes in a couple of seconds.
I find it interesting that the SQLite GnuCash book is 5.5MB and the text ledger is ~800K.

**Comment by MisterY** [comment]
Yes, that works! Thanks, Sebastien. I've submitted a pull request #108.
