### ISSUE TITLE
legder: exporting namespace with the symbol?

### ISSUE THREAD

**Issue by MisterY** [sdementen/piecash#109]
Exporting to ledger refers to commodities only by symbol, i.e. `commodity AUD`.

Adding the namespace (exchange) might be useful, especially for shares. I already have a case where a fund moved from one exchange to another (another country) and, while the symbol is the same, the exchange (namespace) is different.

I'd like to see the opinions on what would be the best way to solve this. Some options I see:

- include namespace in export to ledger. I.e. export "NAMESPACE.SYMBOL" or "SYMBOL.NAMESPACE". The dot is used as column is considered a separator.
- use the above syntax in GnuCash. This requires no change to piecash but does require manual editing of all the securities used, potentially including currencies.

**Comment by sdementen** [comment]
not relevant anymore for user
