### ISSUE TITLE
Options to export book sections to ledger

### ISSUE THREAD

**Issue by MisterY** [sdementen/piecash#110]
The export to ledger seems to work great.

I would like to be able to export specific sections (commodities, accounts, prices, ledger) into separate files. Adding options or arguments to ledger command should be able to easily handle this.

The common scenario would be to export commodities and accounts once and keep them separate from transactions. Using `--strict` option in ledger will ensure that no new commodities or accounts are introduced by accident.

Prices are kept in a separate database anyway.

This would leave only the transactions to be exported frequently and operated on. 

Separating the files allows for easy change comparison when the data files are kept under source control. 

I am currently doing this manually and having options to do it at generation time would help a lot. I'm happy to add options to the click command and try it out. Would you accept this change?

**Comment by sdementen** [comment]
not relevant anymore for user
