### ISSUE TITLE
ledger export - ISO date format

### ISSUE THREAD

**Issue by MisterY** [sdementen/piecash#115]
Since ISO 8601 date format is supported by ledger, it may be more appropriate than YYYY/mm/dd, used currently. 
Perhaps add a parameter to specify the format in the command line.

**Comment by sdementen** [comment]
Yes indeed. Could you make a PR?

**Comment by MisterY** [comment]
Sure. It's probably a simple change. I added the issue here as a reminder while I'm still testing different systems for plain text accounting and various parts of that ecosystem.
