### ISSUE TITLE
include security price when exporting trades to ledger

### ISSUE THREAD

**Issue by MisterY** [sdementen/piecash#118]
During the export of commodity transactions, the records include only the amounts and commodities but not the price: `100 USD @@ 50 EUR`.
Even though the information is redundant to ledger, it might be beneficial to export the price in the transaction split for quick reference.

Need to find appropriate references in the documentation and append here.

**Comment by MisterY** [comment]
Off topic, would it make sense (even though it's just one script) to separate the ledger export from the rest of piecash?

**Comment by sdementen** [comment]
hello @MisterY , I released piecash 1.1. Is the issue still there ?

**Comment by MisterY** [comment]
Hi, @sdementen ! Unfortunately, I can no longer confirm this as I have no valid GNUCash database available.

**Comment by sdementen** [comment]
ok, I close this issue and the other open issues from you (feel free to reopen them if needed)

**Comment by MisterY** [comment]
ok. I may have implemented the features I needed during the migration in my branch. It's only been a year but feels much longer. Quite happy with Ledger so far. I feel I have a better overview and certainly less technical issues. And it works on the phone! :)
