### ISSUE TITLE
Combine selling shares and capital Gain/Loss in one transaction

### ISSUE THREAD

**Issue by pinta-davide** [sdementen/piecash#127]
[Combine Selling shares and capital gain_loss in one transaction.pdf](https://github.com/sdementen/piecash/files/3638904/Combine.Selling.shares.and.capital.gain_loss.in.one.transaction.pdf)

**Comment by sdementen** [comment]
Hello, what is the concrete issue?

**Comment by sdementen** [comment]
Could you post the code you are using so I can reproduce the bug on my side?

**Comment by gorf** [comment]
Is this method right? I use gnucash to record secirity sale with trade account.

**Comment by sdementen** [comment]
You can post it in the thread as a comment.
Do not forget to add three backquotes before and after the code block to have it nicely formatted (there is a preview mode to preview how the post will look like).

And welcome to GitHub ;-)

**Comment by pinta-davide** [comment]
Here's the code:

```
import piecash
from piecash import Transaction, Commodity, Split, Account,ledger
import datetime
from decimal import Decimal

bookPath =  your book path
mybook = piecash.open_book(bookPath, readonly=False, open_if_lock=False)

##set variables
qty = 100
proceeds = 100*250
income = 5000
qty_def = 0  ### i want the quantity to be zero on one of the splits
date = "03/01/2019"
enter_date = datetime.datetime.strptime(date, '%m/%d/%Y')
post_date = post_date = datetime.datetime.strptime(date, '%m/%d/%Y').date()

##get accounts
stock_acct = mybook.accounts.get(name = 'AAPL')
cash_acct = mybook.accounts.get(name = 'Cash Account')
inc_acct = mybook.accounts.get(fullname = 'Income:Capital Gains')

##set commodity
USD = mybook.commodities.get(mnemonic="USD")

#creae transaction
tr = Transaction(currency=USD, description='Test Cap Gain Txn', notes='Long-Term Gain',
                	post_date=post_date,
                	enter_date=enter_date,
                	splits=[
                         	Split(account=stock_acct, value=round(Decimal(-proceeds),6), quantity=round(Decimal(-qty),6), memo='Sale Amount'),
                         	Split(account=cash_acct, value=round(Decimal(proceeds),6), memo='Cash from proceeds'),
				Split(account=inc_acct, value=round(Decimal(-income),6), memo='Cap Gain'),
				Split(account=stock_acct, value=round(Decimal(income),6), quantity=round(Decimal(qty_def)), memo='Cap Gain'),
               		])	
					
print(ledger(tr))
mybook.add(tr)
mybook.save()
```

The error i get is:
value = (self.value / self.quantity).quantize(Decimal("0.000001"))
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]

It's b/c i set the qty_def to zero. But I would like to do this so that i can capture the capital gain (income) in the capital gain account. Via the front end of the GNUCash application, it is possible to enter a transaction like above. See https://www.gnucash.org/docs/v3/C/gnucash-guide/invest-sell1.html.

Again, thank you for the help.

**Comment by pinta-davide** [comment]
gorf-

With the trading accounts, how do you capture the realized capital gain on a security sale into an income account?

best

**Comment by gorf** [comment]
I record the buy and sell normally, without income. Later I use the "view lots" to generate income.

**Comment by sdementen** [comment]
I close the issue as no more activity, feel free to reopen if needed with extra information
