### ISSUE TITLE
Error in online docs

### ISSUE THREAD

**Issue by dpotter4** [sdementen/piecash#128]
I just wanted to point out an error I found in the online documentation. 
See https://piecash.readthedocs.io/en/master/tutorial/index_existing.html .

It says regarding backups "When opening in full access (readonly=False), piecash will automatically create a backup file named filename.piecash_YYYYMMDD_HHMMSS with the original file. To avoid creating the backup file, specificy backup=False as:
book = piecash.open_book("existing_file.gnucash", readonly=False, backup=False)".

This should read:
book = piecash.open_book("existing_file.gnucash", readonly=False, **do_backup**=False .

Thanks for the great work in producing this software. I have found it extremely useful.

**Comment by sdementen** [comment]
You're totally right, well spotted!
Can you issue a pull request to fix it?
