### ISSUE TITLE
Support GnuCash 4.1

### ISSUE THREAD

**Issue by EuPhobos** [sdementen/piecash#136]
This project are dead? Any update?
There is only new version of "splits" table:
gnucash=> select table_name, table_version from versions where table_name = 'splits'; 
 table_name | table_version 
------------+---------------
 splits     |             5

**Comment by peterb12** [comment]
Nice that this patch exists, but it still makes sense to do a new release since anyone using pip installs isn't helped by the patch existing.

**Comment by gregwalters** [comment]
It'd be nice if @sdementen were to make me (or anyone else interested) a maintainer so these type things could be resolved.

**Comment by sdementen** [comment]
@gregwalters with pleasure!
I find my way to make you maintainer with me on the project

**Comment by sdementen** [comment]
maybe worthwile to sync the version of piecash with the version of gnucash (at least on major versions) so we could release packages that support a specific version without needing to make the package multi-version compatible (which is kind of hard given the sqlalchemy models)

**Comment by sdementen** [comment]
@gregwalters I have invited you to collaborate on the project (I am not expert in github access mgt so if I should do something else to give you maintainer role, tell me!)

**Comment by sdementen** [comment]
@gregwalters I see you are now a collaborator. Do you have enough rights?

**Comment by gregwalters** [comment]
Hey @sdementen,

Thanks for taking such quick action on my behalf! I regret I've not been able to reciprocate due to a busy personal schedule. Some time in the next couple of days I plan on taking an in-depth look to confirm.

**Comment by gregwalters** [comment]
Hey @sdementen, can you make me a maintainer on pypi too? Username allrightname.

**Comment by sdementen** [comment]
Hi @gregwalters if I recall correctly (but really not sure), the pypi deployment is done via travisCI once merged into master

**Comment by sdementen** [comment]
@gregwalters when merging a branch, we should ensure that, beyond the code:
- docs are updated
- tests are updated (including gnucash books used for testing)
- changelog are updated

**Comment by sdementen** [comment]
@gregwalters I am also on gitter (https://gitter.im/sdementen/piecash)  if you want to chat online

**Comment by sdementen** [comment]
@gregwalters @EuPhobos could you try the new release of piecash 1.1 and confirm (or not) the issue is fixed ?

**Comment by gregwalters** [comment]
Just tested with the latest and the issue is resolved.
