### ISSUE TITLE
error when importing the piecash module

### ISSUE THREAD

**Issue by pfelecan** [sdementen/piecash#149]
I use from time to time the piecash module, once a year when I need to extract the transaction to transform them in their normalized controllable version. For that reason I wrote a Python program which usually does the job even though I always encounter issues synchronizing GNUcash itself and piecash with all its dependencies.

Today, the issue is at the very begining of the usage, when importing piecash:

`import piecash
`
which yelds the following error:

File "/pariNAma/gnucash-fec/./fecel.py", line 24, in <module>
    import piecash
  File "/usr/local/lib/python3.9/dist-packages/piecash-1.1.2-py3.9.egg/piecash/__init__.py", line 10, in <module>
    from ._common import (
  File "/usr/local/lib/python3.9/dist-packages/piecash-1.1.2-py3.9.egg/piecash/_common.py", line 7, in <module>
    from .sa_extra import DeclarativeBase, _Date
  File "/usr/local/lib/python3.9/dist-packages/piecash-1.1.2-py3.9.egg/piecash/sa_extra.py", line 28, in <module>
    class DeclarativeBase(object):
  File "/usr/local/lib/python3.9/dist-packages/SQLAlchemy-1.4.0b1-py3.9-linux-x86_64.egg/sqlalchemy/orm/decl_api.py", line 606, in decorate
    return self.generate_base(**kw)
TypeError: generate_base() got an unexpected keyword argument 'constructor'

This is on a Debian testing with Python 3.9 as its default.

Is there somebody able to shed light on this issue ?

Thank you in advance

**Comment by pfelecan** [comment]
Addition/simplification: even the example doesn't work :-(
import piecash

with open_book("let2020.gnucash") as book:
    # get default currency of book
    print( book.default_currency )  # ==> Commodity<CURRENCY:EUR>
   
    # iterating over all splits in all books and print the transaction description:
    for acc in book.accounts:
        for sp in acc.splits:
            print(sp.transaction.description)

**Comment by sdementen** [comment]
Can you try downgrading sqlalchemy to 1.3?

**Comment by pfelecan** [comment]
First of all I removed the SQLAlchemy installation made by python.py.
After installing the Debian provided packages, python3-sqlalchemy python3-sqlalchemy-utils, everything went smoothly.
Thank you for your support.

**Comment by sdementen** [comment]
I updated the package so that it installs sqlalchemy<1.4 to avoid the issue you met
