### ISSUE TITLE
Ledger export: transactions not in chronological order

### ISSUE THREAD

**Issue by chrisberkhout** [sdementen/piecash#157]
I think it's becasue of [sorting on `currency_guid` then `post_date`](https://github.com/sdementen/piecash/blob/master/piecash/ledger.py#L182).

I was feeding this into a `leger reg ...` command and getting incorrect numbers. I corrected that by telling Ledger to sort it first (`ledger reg --sort date ...`).

It seems like sorting by date should be the default.

**Comment by sdementen** [comment]
Can you prepare a PR to fix this?
