### ISSUE TITLE
Access to the Notes field of Accounts

### ISSUE THREAD

**Issue by obzerving** [sdementen/piecash#162]
I know that this was referenced in Issue #96, but I'm looking for some further clarification. I would like to access through piecash the information that I put into the Notes field in a similar manner as the Description field. The response to Issue #96 didn't particularly rule out such an enhancement, but it seemed to have been pushed aside to discuss where to specifically place the requestor's unique data. Can access to the Notes field please be revisited? Thanks.

**Comment by sdementen** [comment]
What did you try already to access the notes information?

**Comment by obzerving** [comment]
I can access the Description field of an account by referencing account_object.description. I tried to access the Notes field in a similar way, but there is no method or property named "notes." If there is a way to access the Notes field of an account, I missed it in the documentation and would appreciate a pointer to it.

**Comment by sdementen** [comment]
the "notes" field is stored as a slot in gnucash so to access it you do for instance
`book.accounts(name="Asset")["notes"]`

You can view all the slot fields of a gnucash object with
`book.accounts(name="Asset").slots`

**Comment by obzerving** [comment]
Thanks for your help.
