### ISSUE TITLE
A47 FEC don't grok

### ISSUE THREAD

**Issue by pfelecan** [sdementen/piecash#17]
The example `export_norme_A47.py` is a nice start to conform to the French IRS requirements but, unfortunately it's not groked by their verification tool which is quite annoying.
I'm working on a variation which exports a CSV file which is well understood by the aforementioned tool. If you're interested I can request for a pull.
If you have a better solution please let me know.

**Comment by sdementen** [comment]
You can go for a PR. Tx !



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by pfelecan** [comment]
OK. I'll do that after finishing my tests. Unfortunately Python is not my most familiar language and I think that you'll need some tweaking.

**Comment by sdementen** [comment]
Btw, the script to export to a47 may be better in the sister repo gnucash-utilities instead of this repo

**Comment by pfelecan** [comment]
I agree with you. The pull request will concern that repo.
