### ISSUE TITLE
Fail on Python3 due to thread error?

### ISSUE THREAD

**Issue by guygma** [sdementen/piecash#19]
Hi there - I've had fine performance with Python 2.7, but this package seems to have issues with Python 3.5 or 3.6 both giving the same error:

```
ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 123145415696384 and this is thread id 140736416961472 [SQL: 'SELECT accounts.account_type AS accounts_account_type, accounts.commodity_scu AS accounts_commodity_scu, accounts.non_std_scu AS accounts_non_std_scu, accounts.placeholder AS accounts_placeholder, accounts.guid AS accounts_guid, accounts.name AS accounts_name, accounts.commodity_guid AS accounts_commodity_guid, accounts.parent_guid AS accounts_parent_guid, accounts.code AS accounts_code, accounts.description AS accounts_description, accounts.hidden AS accounts_hidden \nFROM accounts \nWHERE accounts.parent_guid IS NOT NULL'] [parameters: [{}]]
```

This happens when trying to create a new account in a new (or existing) book and then listing the accounts. 

Is this a known issue? I've tried on MacOS 10.12 and Ubuntu MATE 16.04 LTS

**Comment by sdementen** [comment]
Hi, 
in which kind of program are you using piecash ? In a Web server ?
The exception complains about multi-threading use of sqlite which is a setup piecash was never tested explicitly.

**Comment by guygma** [comment]
This is just in an ipython instance.

**Comment by guygma** [comment]
I did just try in a normal python shell and there is no issue, so it seems to be related to how ipython handles multi-threading.

**Comment by sdementen** [comment]
You could try the hint given here Https://stackoverflow.com/a/43538853 (pass to piecash the explicit sqlite connection string and add the check_same_thread=False argument to it)

**Comment by sdementen** [comment]
But I would be extra cautious when using piecash with this flag for modifying gnucash books (i an not familiar at all with these multi-threading issue in sqlalchemy)

**Comment by guygma** [comment]
What I get is a FileNotFound error. I suppose this isn't too big an issue because it *does* work in a non-interactive shell for python3 and in either for python2. It is good to have at least a sense of where the error is coming from.

**Comment by sdementen** [comment]
With the same connection string in a shell and in a jupyter notebook, you get no exception or a FileNotFound exception ? I would suspect some issue re a relative path that is interpreted differently in the shell vs in jupyter. What connection string are you using ?

**Comment by guygma** [comment]
I get a FileNotFound when using a string like `"file.gnucash?check_same_thread=False"`. I only tried that jupyter given that is where the threading issue exists. It seems to me more like an issue of how piecash is interfacing with sqlalchemy but you know the underpinnings better than I do obviously.

**Comment by sdementen** [comment]
You need to use the uri_conn argument when opening your gnucash book as shown in http://piecash.readthedocs.io/en/latest/tutorial/index_existing.html#opening-an-existing-book and there specify the check_same_thread=False. 
For the construction of the sqlite uri_conn on Mac OS you can look at http://docs.sqlalchemy.org/en/latest/core/engines.html#sqlite on how to specify the full path of your gnucash file (if the relative path does not work in jupyter)

**Comment by guygma** [comment]
That did it. Oddly (to me, perhaps not to you) I get an error still if I included the `readonly=False` option, but once that was removed it worked and I could also still write to the file. I've not looked much at how the syntax changes when using `uri_conn` so the reason for this may be trivial.

**Comment by sdementen** [comment]
With readonly=False, can you try to add the do_backup=False to see if it removes the error ?
Otherwise, what error do you get with the readonly=False ?

**Comment by guygma** [comment]
Here is the error I get:

```
In [13]: book = piecash.open_book(uri_conn='sqlite:///mfbooksq.gnucash?check_same_thread=False', readonly=False)
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-13-0f239c7b210b> in <module>()
----> 1 book = piecash.open_book(uri_conn='sqlite:///mfbooksq.gnucash?check_same_thread=False', readonly=False)

/usr/local/lib/python3.5/dist-packages/piecash/core/session.py in open_book(sqlite_file, uri_conn, readonly, open_if_lock, do_backup, db_type, db_user, db_password, db_name, db_host, db_port, **kwargs)
    238         url_backup = url + ".{:%Y%m%d%H%M%S}.gnucash".format(datetime.datetime.now())
    239
--> 240         shutil.copyfile(url, url_backup)
    241
    242     locks = list(engine.execute(gnclock.select()))

/usr/lib/python3.5/shutil.py in copyfile(src, dst, follow_symlinks)
    112         os.symlink(os.readlink(src), dst)
    113     else:
--> 114         with open(src, 'rb') as fsrc:
    115             with open(dst, 'wb') as fdst:
    116                 copyfileobj(fsrc, fdst)

FileNotFoundError: [Errno 2] No such file or directory: 'mfbooksq.gnucash?check_same_thread=False'
```
If I include the `do_backup=False` option the error does go away, I can add an account, and save to file.

**Comment by sdementen** [comment]
OK, the issue is in the code that make a backup of the sqlite file automatically when in read/write mode that cannot handle the extra parameter. 
Better to add a sqlite_thread_unsafe argument to the open_book  that manages this issue

**Comment by sdementen** [comment]
I am trying to reproduce the bug with:
- windows
- python 3.6.1
- piecash 0.13.0
- jupyter
and the following code in jupyter
```
with piecash.open_book("foo.gnucash",readonly=False,do_backup=True) as b:
    print(b.accounts)
```
and I can't reproduct the issue (the foo.gnucash was created by piecash itself).
Could you send me the jupyter notebook that raises the issue ?
