### ISSUE TITLE
doesn't work with splits table version 5

### ISSUE THREAD

**Issue by SudoMike** [sdementen/piecash#191]
Using a sqlite3 file in gnucash 4.7, piecash fails when calling open_book() with, "Unsupported table versions". Debugging in, the problem is that versions_supported has splits=4 and the file I'm trying to open has splits=5.

**Comment by sdementen** [comment]
This means gnucash may have changed the format of the splits table. Do you know if this is the case?
If not, you can change the splits version in the code to accept version 5 but it may be risky for your data...

**Comment by SudoMike** [comment]
Actually, it looks like the latest piecash fixes this. I was using v1.0.0 (from an old requirements.txt file). Closing this out, nothing to see here..

**A few notes on this change to the splits table for posterity:**

It looks to me like they changed all their sql TIMESTAMP fields to DATETIME in Nov 2017 [here](https://github.com/Gnucash/gnucash/commit/9c4635e3930f6026080cf18ea7ca92133733c944). They upped the Transactions table version from 3 to 4 there, but they forgot to update the Splits table version.

Then in July 2019, they committed [a change](https://github.com/Gnucash/gnucash/commit/e88f31e05cd57ba6fcc07563d98fb55c5310d25d) that only changed the Splits table version to account for the change they'd made **2 years prior**.
