### ISSUE TITLE
The importance of Decimal?

### ISSUE THREAD

**Issue by tim-rohrer** [sdementen/piecash#206]
Working on a migration project, I'm using a mapper class to prepare my data for ingestion by `Split`.

```
@dataclass
class Split2Move:
    """Class to keep track of splits to be moved."""

    account: str
    value: str
    memo: str
```

In doing so, I realized that I did not explicitly use `Decimal` on the string `value`, and I subsequently mapped the data into `Split`. The code appears to work. 

In looking at `Split` code in the docs, I see `self.value = value`, but nothing that converted it to `decimal:Decimal`.

Should my code have worked? Is this an accident (bug) waiting to happen?

I realize I can (and probably should) change my `dataclass` to enforce the attribute type, but I wanted to try and understand the situation better.

Thanks.

**Comment by sdementen** [comment]
Are you using the sqlite backend? If so, the sqlite backend is quite flexible in what it accepts.
Do you get back Decimals?

**Comment by sdementen** [comment]
Looking at https://stackoverflow.com/questions/58649529/how-to-create-multiple-memory-databases-in-sqlite3, it seems that you need to use named in memory databases to avoid all these to point to the same database (and having cryptic error messages)

**Comment by tim-rohrer** [comment]
Turns out the test issue was related to my inexperience with python variables, and how this pattern:

```python
for f in f_list:
  f.element = some_other_value
```
actually mutates `f_list`. 

:sheepish_grin:

Thanks again for your help.
