### ISSUE TITLE
Introduce additional fields to splits_df

### ISSUE THREAD

**Issue by NigelCleland** [sdementen/piecash#21]
Splits_df is currently missing some critical information. Namely the transaction guid and the transaction description. This makes it quite difficult to link transactions together using piecash for further analysis.

The relevant code that needs to be changed is on: https://github.com/sdementen/piecash/blob/master/piecash/core/book.py#L473 

**Suggestion:**

1. Add additional items to fields, namely, transaction.guid, memo and transaction.description
2. Introduce an additional fields parameter to the splits_df function.

```
def splits_df(self, optional_fields=list())
        # Existing Code here
        # build dataframe
        fields = ["guid", "value", "quantity", 'memo', 'transaction.guid', 'transaction.description',
                  "transaction.post_date", "transaction.currency.guid", "transaction.currency.mnemonic",
                  "account.fullname", "account.commodity.guid", "account.commodity.mnemonic",
                  ] + optional_fields
...
```

If you're happy with the proposal solution I can raise a pull request and send it through.

**Comment by sdementen** [comment]
Yes, please do so!
If you could even add a unit test, even better !



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
