### ISSUE TITLE
Unicode Support

### ISSUE THREAD

**Issue by rosaldanha** [sdementen/piecash#3]
Hello, when I try to list my accounts, using the provided example, I got the following error:
```
Account<Despesas[BRL]>
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/piecash-0.7.4-py2.7.egg/piecash/core/account.py", line 251, in __repr__
    return "Account<{}[{}]>".format(self.fullname, self.commodity.mnemonic)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 1: ordinal not in range(128)
```
Thanks

**Comment by sdementen** [comment]
Could you try editing the related file on line 251 by changing the line to :
return **u**"Account<{}[{}]>".format(self.fullname, self.commodity.mnemonic)

I think it should work but can't test it right now.

**Comment by rosaldanha** [comment]
Thank you ! It worked.

**Comment by sdementen** [comment]
version 0.8.1 should be saner regarding unicode handling
