### ISSUE TITLE
replace 'yahoo-finance'

### ISSUE THREAD

**Issue by sdementen** [sdementen/piecash#32]
The yahoo-finance package relied on a non-official API from yahoo that got discontinued on 2017-11-01.
See how to replace it by http://alpha-vantage.readthedocs.io/

**Comment by rerobins** [comment]
Please don't use the alpha-vantage python library.  It requires pandas to do data analysis which is not needed to fetch data.

**Comment by sdementen** [comment]
You do not want to have a dependency on pandas if I understand correctly ;-)
I agree it is a bit heavy but for my personal curiosity, could you tell me the pains you have with installing pandas?
Could it be an option to work upstream with the alpha vantage python module to remove it (or make it optional)?
Or should we just call the API with requests in piecash ?

**Comment by rerobins** [comment]
Correct.

I think it may just be easier to implement the functionality you want with requests.  The alphavantage library is used to do analysis on the data, noy provide access. 

I wrote something similar last night and its only about 10 lines to fetch stock/fund prices.

**Comment by sdementen** [comment]
Indeed.
If you want to have a try at the implementation of this feature, do not hesitate !

**Comment by sdementen** [comment]
Close as other project already provided the feature https://github.com/belidzs/gnucash_quotes
