### ISSUE TITLE
get commodity balance

### ISSUE THREAD

**Issue by MisterY** [sdementen/piecash#35]
Is there a way to get a commodity balance in the whole book (meaning, across all accounts)? If not, let's add it. Any pointers are welcome.

I have a general issue with GnuCash in that I can not easily see the balance of certain security (commodity), i.e. fund, that was purchased with different brokers. In all the reports these are shown as separate lines and I'd have to add them manually.
Any thoughts? I might add this at a higher level, like utilities, or portfolio repos.

**Comment by sdementen** [comment]
I guess that with the df_* methods of the book, you can quicky write a pandas expression to do what you want.
Would be useful to get a complex gnucash book example to test this kind of reports. There are couple of books on the repo but none very complex.

**Comment by MisterY** [comment]
Hm, the good thing is that it is possible to get the .accounts[] collection per security. Is there a way to get the current balance of an account? That would solve everything. 
And, Murphy's Law states that this is exactly why it is not possible. :)

**Comment by sdementen** [comment]
can http://piecash.readthedocs.io/en/latest/api/piecash.core.account.html#piecash.core.account.Account.get_balance help ?

**Comment by MisterY** [comment]
Wonderful! 
However, doesn't help straight away. :(
I'll have a look later but that's a good pointer.
I'm trying to add all the balances [here](https://github.com/MisterY/gnucash-portfolio/blob/master/src/symbol_balance.py) and am getting:
```
VTIP 198.24
VTIP -1631.51
VTIP 1433.27
0.00
```
So, two things:
1) I need to use Decimal for the Total and, more importantly,
2) The balances seem to be in the real currency (USD). And, I'm not sure what exactly they are.

But, as I've said, that's a good pointer. There must be balances available in the number of shares of a fund, instead of in $. Thanks!

**Comment by MisterY** [comment]
comment updated :)

**Comment by sdementen** [comment]
could you upload a sample of your book (potentially anonymised thanks to piecash ;-))

**Comment by MisterY** [comment]
I see. There is a need for quantity_num, quantity_denom values to be exposed. That gives the number of units in the fund.
If you give me a quick pointer as to how to anonymize the data, I'll gladly do it (but I need to leave in 5 mins, so perhaps I do it later tonight).

**Comment by sdementen** [comment]
normally, you should use the quantity field (it wraps the quantity_num, quantity_denom in a python Decimal object)
for anonymisation of book, I was thinking about a customer script that does random renaming of accounts + random variations of amounts / currencies. But nothing exists yet.

**Comment by MisterY** [comment]
I updated the script in the meantime (I was just working on it) with Decimal, etc.

Now, just a new method needs to be created on Account that iterates through Splits and, instead of the $ amount, uses the amount in the commodity (from quantity fields). Perhaps I assemble something later tonight.

**Comment by MisterY** [comment]
Resolved in #36
