### ISSUE TITLE
export AccountType

### ISSUE THREAD

**Issue by MisterY** [sdementen/piecash#37]
I am not sure why exporting AccountType from .account doesn't work - the scripts that utilize piecash don't see it if it is added to __init__.py.
It would be useful to have it available publicly. For example, when filtering out the trading accounts.
Any hints? Thanks!

**Comment by MisterY** [comment]
Oh, I meant the enum. I'd like to compare account.type to AccountType.trading.

**Comment by sdementen** [comment]
you can refer to it as AccountType.trading for the TRADING account type.
can you post an example of code for what you would like to do ?

**Comment by MisterY** [comment]
If you look at this new test, for example, I'm skipping the trading accounts when calculating the quantity. Now, instead of comparing account.type == "trading", I'd like to compare if account.type == AccountTypes.trading, but the enum is not accessible (exported).

**Comment by sdementen** [comment]
ok, got it

**Comment by sdementen** [comment]
@MisterY is the issue still there ? any PR ? tx!

**Comment by MisterY** [comment]
I'll have to revisit. I copied the enum to solve the problem initially but now I know more about Python so I know how to expose it. It seems to work in my initial test but I'll still need to write a test or two for it, both in the Portfolio project and Piecash. Cheers!
