### ISSUE TITLE
Piecash crashes when float is used instead of a Decimal.

### ISSUE THREAD

**Issue by gregorias** [sdementen/piecash#39]
In piecash 0.13.0, the following program:

```
import datetime
import piecash as pc

book = pc.create_book(currency="USD")
USD = book.commodities.get(mnemonic="USD")
a = pc.Account(name="A", type="ASSET", parent=book.root_account, commodity=USD)
b = pc.Account(name="B", type="ASSET", parent=book.root_account, commodity=USD)
sa = pc.Split(account=a, value=-4020.19, quantity=-4020.19)
sb = pc.Split(account=b, value=4020.19, quantity=4020.19)
pc.Transaction(
    currency=USD,
    description='',
    splits=[sa, sb],
    post_date=datetime.datetime.strptime('2017-11-18', '%Y-%m-%d'))
book.accounts
```

crashes with `OverflowError: Python int too large to convert to SQLite INTEGER`.

The cause is the use of floating point numbers. In https://github.com/sdementen/piecash/blob/9d4c33c3770ac1a1bf5e1f2456f7f42b6070b9c4/piecash/_common.py#L52-L60

the float is converted to `Decimal('4020.19000000000005456968210637569427490234375')`, which is too large to be represented within even the largest - 8-byte - INTEGER.

Is there anything you'd like to be done about it? I think that we should at least make sure that the exception points to the root cause, because it took me some time that it was caused by the use of a floating point number. Note that the exception is triggered in the `book.accounts` line and not when the offending Transaction is created.

We could add a warning against float or truncation to warn users against using floats.

**Comment by sdementen** [comment]
Maybe raise a TypeError exception when using float (str ,int and long should be ok) with a message like "gnucash/piecash works with Decimals for exact arithmetic. You can use Decimal, str, int or long types for numbers"
