### ISSUE TITLE
Incorrect account balance

### ISSUE THREAD

**Issue by MisterY** [sdementen/piecash#45]
Just a heads up. The account get_balance() returns a value different to what is displayed in GnuCash for some (cash) accounts.
I will investigate further why this is the case.

The result is visible in Cash Balances report in gnucash_portfolio.
Quick number adding manually, by using 
```
select *, quantity_num / quantity_denom from splits sp
	left join transactions tx on sp.tx_guid = tx.guid
where account_guid = 'f0796848811ac0ad659e41e95b90e9fc'
order by tx.post_date
```
produces a value that's closer to GnuCash.
get_balance() gives me a negative value (-190.91 vs 6.65 in GnuCash).

**Comment by MisterY** [comment]
OK, I think I got it. 
What's going on is the following:
I'm looking at the balance for Acc[USD]. There are transfers from Acc[EUR] to Acc[USD].
get_balance() uses all splits, including transfers, which look like this:
```
Acc[USD] +100
Trading:CURRENCY:USD -100
Trading:CURRENCY:EUR +80
Acc[EUR] -80
```

Acc[USD].splits includes amounts in EUR, which are part of the above split.
When I print the splits, they show correctly:
```
Split<Account<Acc[USD]> 80.00 EUR [100.00 USD]>
```
These numbers are stored in Value (EUR) and Quantity (USD).

However, get_balance() **only** uses Value, which in this case takes the amount in Euros, not USD.

**Comment by MisterY** [comment]
The conclusion is that the parent transaction's currency will have to be taken into account when choosing which field to add.
Pull request to follow.

Helper command, to help me troubleshooting later:
```
select * from transactions tx
	left join splits sp on tx.guid == sp.tx_guid
where tx.guid = '4f829349276b7fa0a421d9d0f6b74ef4'
```

**Comment by sdementen** [comment]
shouldn't the get_balance be in fact the get_quantity function (https://github.com/sdementen/piecash/blob/master/piecash/core/account.py#L260) ?

**Comment by MisterY** [comment]
Hi! Please have a look at the comment above, which I keep updating.
I think that, when the tx.currency doesn't match the account, then the quantity is used.

**Comment by sdementen** [comment]
If the tx.currencty match the account, value=quantity ==> in all cases, isn't quantity the good number to add for balance ?

**Comment by MisterY** [comment]
Could be. I'm not 100% sure at the moment as I tend to use 5 min. at a time to look at it. Will solve later tonight, definitely. You may be completely right.

**Comment by MisterY** [comment]
Ah, yes, I see what you mean. Yes, quantity is the correct field, to use!

**Comment by MisterY** [comment]
Right, now the cash balance report is correct. Thanks!
