### ISSUE TITLE
Update support for Prices table

### ISSUE THREAD

**Issue by MisterY** [sdementen/piecash#49]
After upgrade to GnuCash 2.7.2, the following error is thrown by Session:
`
AssertionError: Unsupported version for table prices : got 3, supported 2
`
What's the idea with supporting the table updates? I could compare the schema and see if they are still compatible.

**Comment by sdementen** [comment]
indeed, it is precisely to force a check on the schema of the table in case of changes ==> compare schemas of sqlite book created in GC 2.6 and GC 2.7

**Comment by MisterY** [comment]
2.6:
```
CREATE TABLE prices (guid text(32) PRIMARY KEY NOT NULL, commodity_guid text(32) NOT NULL, currency_guid text(32) NOT NULL, date text(14) NOT NULL, source text(2048), type text(2048), value_num bigint NOT NULL, value_denom bigint NOT NULL)
```
GC 2.7
```
CREATE TABLE "prices"(guid text(32) PRIMARY KEY NOT NULL, commodity_guid text(32) NOT NULL, currency_guid text(32) NOT NULL, date text(19) NOT NULL, source text(2048), type text(2048), value_num bigint NOT NULL, value_denom bigint NOT NULL)
```

**Comment by MisterY** [comment]
Diff:
The date field has been increased from 14 chars to 19.

**Comment by MisterY** [comment]
However, I see no change in data
```
20171110230000
20171111230000
```
Should I update the version for Prices in supported versions list?

**Comment by MisterY** [comment]
As noted in the Gnucash commit (link in the pull request), the date format will change soon to be ISO (yyyy-mm-dd HH:mm:ss) instead of custem (yyyymmddhhmmss).
