### ISSUE TITLE
Handle ISO dates

### ISSUE THREAD

**Issue by MisterY** [sdementen/piecash#52]
Hm, as a matter of fact, GC 2.7.2 already stores the dates in ISO format.
The new records have `1970-01-01 00:00:00` values in the field.

Hence I'm getting 
`ValueError: Couldn't parse datetime string: '1970-01-01 00:00:00'` errors on any table that has records with the new format. 
The errors appear on anything that uses Split entity, like simple get_balance() calculation on Account.
Or a query like
```
splits = book.session.query(Split).filter(Split.account == income_account).all()
```

**Comment by MisterY** [comment]
This is a mess. I will update all my existing date to ISO format just so I can continue using the utilities and reports I created recently.

**Comment by MisterY** [comment]
Actually, I'm going back to 2.6. GC startup is just getting abysmall. It takes several minutes to start so I can't really use it. Let's try to work the issue with the dates somehow before the official release of 2.8.

**Comment by sdementen** [comment]
ok

**Comment by sdementen** [comment]
fixed on master
