### ISSUE TITLE
drop support of python 2.7

### ISSUE THREAD

**Issue by sdementen** [sdementen/piecash#53]
hello,

I would like to drop support for python 2 and support only python >= 3.5 for piecash 0.15 and onwards. The old version will still be available for python 2.

Anyone seeing issue with this move ?

**Comment by MisterY** [comment]
Please. Let's push the change from Python 2 to 3. It's been out for nine years already. That's plenty of time to upgrade code, I think.

**Comment by EvansMike** [comment]
GnuCash is still transitioning to Python3 so you may want to wait a bit as some things will stop working using Python3.  https://bugs.gnucash.org/show_bug.cgi?id=797177 is an example.

**Comment by sdementen** [comment]
Not sure how

**Comment by EvansMike** [comment]
Ah, OK. I clearly misunderstood how piecash interacts with GnuCash. I assumed it used the GnuCash Python bindings.

**Comment by sdementen** [comment]
Piecash is indeed independent of gnucash and a 100% python library (no need for compilation, so it even works on Android).
It interacts directly with any gnucash book that uses an SQL backend.

**Comment by sdementen** [comment]
fixed with 1.0.0
