### ISSUE TITLE
Default run of `py.test` or `tox` has test failures

### ISSUE THREAD

**Issue by spookylukey** [sdementen/piecash#54]
With `tox -e py27` I get errors like the following:

    ______________________________ TestCommodity_create_prices.test_update_stock_prices[None]    
    self = <test_commodity.TestCommodity_create_prices object at 0x7fb9136c00d0>, book_basic = Book<sqlite:///:memory:>
    
        def test_update_stock_prices(self, book_basic):
            if not is_inmemory_sqlite(book_basic) or is_not_on_web():
                print("skipping test for {}".format(book_basic))
                return
            cdty = Commodity(mnemonic="AAPL", namespace="NASDAQ", fullname="Apple", book=book_basic)
            cdty["quoted_currency"] = "USD"
            assert cdty.get("quoted_currency") == "USD"
    >       cdty.update_prices()
    
    tests/test_commodity.py:121: 
    _ _ _ _  _ 
    piecash/core/commodity.py:237: in update_prices
        share = yahoo_finance.Share(symbol)
    .tox/py27/lib/python2.7/site-packages/yahoo_finance/__init__.py:182: in __init__
        self.refresh()
    .tox/py27/lib/python2.7/site-packages/yahoo_finance/__init__.py:146: in refresh
        self.data_set = self._fetch()
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    self = <yahoo_finance.Share object at 0x7fb913223f10>
    
        def _fetch(self):
            data = super(Share, self)._fetch()
    >       if data['LastTradeDate'] and data['LastTradeTime']:
    E       TypeError: list indices must be integers, not str
    .tox/py27/lib/python2.7/site-packages/yahoo_finance/__init__.py:186: TypeError

And similarly with Python 3.5

Strangely I get a different error when I don't go via `tox` and instead do `python setup.py test` or `py.test`:

    ________________ TestCommodity_create_prices.test_update_stock_prices[None] 
    
    self = <test_commodity.TestCommodity_create_prices object at 0x7f8260a653c8>, book_basic = Book<sqlite:///:memory:>
    
        def test_update_stock_prices(self, book_basic):
            if not is_inmemory_sqlite(book_basic) or is_not_on_web():
                print("skipping test for {}".format(book_basic))
                return
            cdty = Commodity(mnemonic="AAPL", namespace="NASDAQ", fullname="Apple", book=book_basic)
            cdty["quoted_currency"] = "USD"
            assert cdty.get("quoted_currency") == "USD"
    >       cdty.update_prices()
    
    tests/test_commodity.py:121: 
    _ _ _ _ _ _ _ _ _ _ _ _ _
    piecash/core/commodity.py:237: in update_prices
        share = yahoo_finance.Share(symbol)
    ../../.virtualenvs/piecash/lib/python3.5/site-packages/yahoo_finance-1.4.0-py3.5.egg/yahoo_finance/__init__.py:178: in __init__
        self.refresh()
    ../../.virtualenvs/piecash/lib/python3.5/site-packages/yahoo_finance-1.4.0-py3.5.egg/yahoo_finance/__init__.py:142: in refresh
        self.data_set = self._fetch()
    ../../.virtualenvs/piecash/lib/python3.5/site-packages/yahoo_finance-1.4.0-py3.5.egg/yahoo_finance/__init__.py:181: in _fetch
        data = super(Share, self)._fetch()
    ../../.virtualenvs/piecash/lib/python3.5/site-packages/yahoo_finance-1.4.0-py3.5.egg/yahoo_finance/__init__.py:134: in _fetch
        data = self._request(query)
    _ _ _ _ _ _ _ _ _ _ _ _
    
    self = <yahoo_finance.Share object at 0x7f8260a82e80>, query = 'select * from yahoo.finance.quotes where symbol = "AAPL"'
    
        def _request(self, query):
            response = yql.YQLQuery().execute(query)
            try:
                _, results = response['query']['results'].popitem()
            except (KeyError, StopIteration, AttributeError):
                try:
                    raise YQLQueryError(response['error']['description'])
                except KeyError:
    >               raise YQLResponseMalformedError()
    E               yahoo_finance.YQLResponseMalformedError: Response malformed.
    
    ../../.virtualenvs/piecash/lib/python3.5/site-packages/yahoo_finance-1.4.0-py3.5.egg/yahoo_finance/__init__.py:125: YQLResponseMalformedError

If I run with `DONOTGOONWEB=True` then the error disappears, which must be why Travis passes.

**Comment by sdementen** [comment]
The yahoo finance functionality is broken which make the related tests fail.
The difference between tox and test is maybe due to a different collection and execution order of the tests... To check.
Re testing, the call to the web should be mocked to avoid making real calls at each run

**Comment by sdementen** [comment]
I have adapted in master the logic to have per default no call to the web
