### ISSUE TITLE
OverflowError: Python int too large to convert to SQLite INTEGER

### ISSUE THREAD

**Issue by MisterY** [sdementen/piecash#58]
Hey! Long time no see. :)
I've got a funny error appearing for some accounts and I can't yet find the reason. I'll post it here for reference and if you would have any suggestions. The query looks pretty harmless:
```
            self.book.session.query(Account)
            .join(Commodity)
            .filter(Account.name == self.security.mnemonic)
            .filter(Commodity.namespace == "CURRENCY")
            .filter(Account.type != "TRADING")
```
and it generates SQL that executes on SQLite database without any issues.
The confusing thing is that this fails only for some accounts, while most of them work just fine.

Not that it is relevant but just as a background, here I'm searching for income accounts for a security. They have the same name as the the security symbol and are expressed in a real currency, this being my convention to identify matching income accounts.

**Comment by MisterY** [comment]
Hmmm, this just went away without me doing anything meaningful except killing some hanging Python processes. Will reopen if it appears.
I can now open the problematic accounts so it's probably not the code.

**Comment by MisterY** [comment]
Actually, the only thing I changed is to replace the comparison to account type in strings (Account.type == "INCOME" or Account.type != "TRADING") at a few places to enum values (i.e. Account.type == AccountType.INCOME.value).

**Comment by MisterY** [comment]
OK, definitely that. After switching to enum.value, the issue went away because I made a mistake and the query was now comparing "Account.type == 6". So, it was using value intead of name of the enum item.

Switch the comparison to "Account.type == AccountType.INCOME.name" results in comparison by text "INCOME" and now it fails again. So, still something there.
I've seen similar error elsewhere in intrawebs.

Could be something to do with 32/64-bit architecture. I'm using 32-bit Python on 64-bit machine. Not sure about SQLite.

**Comment by sdementen** [comment]
Did you try with the echo / debug flag of sqlaclhemy ? To see what exact query is sent to SQLite ?

**Comment by MisterY** [comment]
Yep. It's clean SQL, as expected. Nothing unusual. Besides, it also works for other accounts. 
```
SELECT accounts.account_type, accounts.commodity_scu, accounts.non_std_scu, accounts.placeholder, accounts.guid, accounts.name, accounts.commodity_guid, accounts.parent_guid, accounts.code, accounts.description, accounts.hidden
FROM accounts
WHERE 'b8b9cf2b1054ea44782218b8fa0b8dc3' = accounts.commodity_guid AND accounts.account_type != 'TRADING'
```

**Comment by MisterY** [comment]
Funny, if I remove the comparison to the account type 
`# .filter(Account.type != AccountType.TRADING.name)`
then everything works.
```
SELECT accounts.account_type, accounts.commodity_scu, accounts.non_std_scu, accounts.placeholder, accounts.guid, accounts.name, accounts.commodity_guid, accounts.parent_guid, accounts.code, accounts.description, accounts.hidden
FROM accounts
WHERE 'b8b9cf2b1054ea44782218b8fa0b8dc3' = accounts.commodity_guid
```

**Comment by MisterY** [comment]
"type" is marked as a keyword on Account class. Can that have something to do with this?

**Comment by MisterY** [comment]
BINGO

**Comment by MisterY** [comment]
I've renamed it to .typex and adjust a few lines and now the page opens.

**Comment by MisterY** [comment]
I'll rename the property to acc_type in order to be able to continue working. Let me know if the name changes to something else. Not sure why this is a problem ,though, as it works for some accounts.

**Comment by MisterY** [comment]
So confusing. Once I renamed .type to .typex, it opened the page. When I renamed to acc_type across the whole class, it again started throwing the exception.

**Comment by sdementen** [comment]
can you look in the sqlite DB what is in the column type ? an integer or a string (like 'TRADING') ?
I would guess it is an integer and than when you use the string 'TRADING' SQLite tries to convert the string "TRADING" into some integer ... but it is an highly speculative guess

**Comment by MisterY** [comment]
No, it's string. The types are also correctly defined in Account, from what I can see. Checked that earlier, nothing glaringly obvious. The field has the same definition as other text fields on the Account table, both in SQLite and PieCash.

**Comment by MisterY** [comment]
Phew, I found the cause. FYI.
The direct, techical, cause is that
```
UPDATE splits SET value_num=?, value_denom=?, quantity_num=?, quantity_denom=? WHERE splits.guid = ?
```
with parameters 
```
[0]:2377208162783362582794846703
[1]:1000000000000000000000000
[2]:194583
[3]:100
[4]:'5145e59fcbdf3e753a0f43b21be2f070'
```
fails. Which is understandable, as the values are huge for the first two numbers.
However, the real reason is that I did some calculation of the average price for securities (as described in https://github.com/MisterY/gnucash-portfolio/issues/33). In the process, I adjust the numbers on the purchased split that has been partially sold.
And, it seems, that this change, even though I do not indend to save the changes but just use them elsewhere for adding the correct numbers, gets flushed in one of the queries in the pipeline, causing the above error in the process. Fortunately, this popped up and the record was not saved as it would destroy the records. The database is readonly at the moment, but this could have happened in a different scenario, which would be really bad. 
I'll have to think what is the best approach to solve the calculation.

**Comment by sdementen** [comment]
ok, normally flushing the data is different than saving the data. If you do not do a book.save(), the changes are not "committed" (i.e. the SQL transaction is rolled back) ==> worth to check that it works (but I have test for that like https://github.com/sdementen/piecash/blob/master/tests/test_book.py#L39)

**Comment by MisterY** [comment]
I would like to eventually get to the bottom of this. Not sure what a good test would be. What I was doing is described in the above issue - modifying the quantity of the split that was partially sold. I'm not sure at which point the overflow kicked in. It should be possible to reproduce on the existing database with a bit of effort in reverting the code. 
The issue is definitely solved by using a model class to store the modified values.

**Comment by sdementen** [comment]
The test to write may be simply to write a transaction with a huge Decimal.
Now, we could add some code in hybrid_property_gncnumeric that would control the Decimal is not too big (in its numerator/denominator form)

**Comment by MisterY** [comment]
What fascinated me is that the value that is assigned should be smaller than the value that was already there. The amount of sold stocks gets subtracted and the remains written to the property.
However, I'm away from the computer this week so won't be able to do much until I'm back.

**Comment by sdementen** [comment]
The issue is not really the "smaller" in a amount, but the smaller in Decimal representation
```
# example
>>> from decimal import Decimal               
>>> d=Decimal("4")                            
>>> d                                         
Decimal('4')            
>>> d - d/3                                   
Decimal('2.666666666666666666666666667')      
```
You can see that 2.6666... is smaller than 4 but the exact representation not!
GnuCash represents the number in the database as a numerator/denominator with both being integers and denominator being limited to some size (I think 2**63-1=9223372036854775807).
So d = Decimal("4") = 400 / 100 (as often cents are used as basis)
d - d/3 = 2666666666666666666666666667 / 1000000000000000000000000000
where are both too large (>2**63-1)

So, you need to explicitly round your values before assigning them to GnuCash values.

**Comment by MisterY** [comment]
Right. But, since I was simply *subtracting* the amount that was sold from a lot, there should not be any divisions like in the case above, which would explain the large Integer. Also, I have nowhere triggered the save method, which made this all the more confusing. 😁

**Comment by sdementen** [comment]
You used Decimals end-to-end in the calculations ? If so, could you get the details of the calculations?
The flushing to the DB is done automatically on some operations but it is not saved to the DB

**Comment by MisterY** [comment]
The explanation would apply if I was also recalculating the remaining value of the stock, not only the quantity. Can't remember right now.
Your change might prevent the exception in the future and point to the right place in the code which causes the issue.
It is great, though, to be able to debug the whole stack in Python and not only one's own code. That helps a lot. I would have never found the real reason for this issue otherwise.

**Comment by MisterY** [comment]
Yes, the calculation is on the Security Details page in the Portfolio project. It calculates the average price of the remaining stock, among other things.

**Comment by MisterY** [comment]
Securities Controller, Details method, I believe. Will try to get the url on GitHub.

**Comment by MisterY** [comment]
https://github.com/MisterY/gnucash-portfolio/blob/master/app/controllers/securities_controller.py#L63
