### ISSUE TITLE
Add Number column to the ledger export

### ISSUE THREAD

**Issue by MisterY** [sdementen/piecash#68]
Comparing to pygnucash output, I see "Est." value from the Number column:
```
2005/11/01 * (Est.) GRAWE Osiguranje d.d.
	Income:Grawe Profit Sharing                   -93.88 BAM
	Assets:Fixed Assets:GRAWE Insurance            93.88 BAM
```
In piecash's output it is missing. It is worthwile adding this info?
It is nice, though, to have the notes exported!
```
2005/11/01 * GRAWE Osiguranje d.d.
	;€48.00
	Income:Grawe Profit Sharing                  -93.88 BAM
	Assets:Fixed Assets:GRAWE Insurance           93.88 BAM
```

**Comment by sdementen** [comment]
What would you want exactly ? adding the "(Est.)" string in the description ? if so, what would be the rule to have this string or not ?

**Comment by MisterY** [comment]
"Est." is the value of the Num column in GnuCash for this transaction. I see that it is added into parenthesis for Ledger to parse.
You could simply include it if it is available and skip if num column is empty. 
The value itself seems to be enclosed in parenthesis and separated by one space from other values.

**Comment by sdementen** [comment]
It is fixed in master
