### ISSUE TITLE
Cannot open gnucash files

### ISSUE THREAD

**Issue by jottr** [sdementen/piecash#7]
When trying to open gnucash files with piecash like so: 

```python
# open gnucash database as writeable 
book = pc.open_book("/tmp/foo.gnucash", readonly = False, open_if_lock = True)
```

I always receive the following error: 
```
DatabaseError: (DatabaseError) file is encrypted or is not a database u'SELECT gnclock.hostname, gnclock.pid \nFROM gnclock' ()
```

I am not sure what could be causing this. 
Recreated the file from scratch several times, then tried to save the file with "Save As" and with "Export" commands, which both yield the same error.

```
Gnucash 2.6.5
Python 2.7.10
```

Here's a [gist](https://gist.github.com/jottr/281c46ad628fa9272ccd) with full stack trace and `ledger.gnucash` for testing.

Also ran `pip install -U piecash` just to be safe.

**Comment by sdementen** [comment]
Could you confirm your gnucash file is saved as "sqlite" (and not as xml) ?
If so, if your gnucash file contains no sensibe data, could upload it so that I could try reproducing the bug ?

**Comment by sdementen** [comment]
I just looked at your gist and you are working with a book saved in XML. Piecash works on books saved with one of the sql backends (sqlite, postgres and mysql). The easiest for you would be to save the book with a "data format" set to sqlite3.
If you do not see the sqlite3 format, you could look at the following blog post http://robertbasic.com/blog/gnucash-4-2-with-sqlite3-on-gnu-linux

**Comment by jottr** [comment]
Found it! Did not see that option earlier. 
Thank you for helping out.

**Comment by soroosh-sdi** [comment]
Update: on ubuntu 24.04 you need to install the libdbd-sqlite3 package to see the sqlite option in the save as form.
