### ISSUE TITLE
Ledger export: Transaction does not balance

### ISSUE THREAD

**Issue by MisterY** [sdementen/piecash#70]
I have a few investment transactions that ledger is complaining about. These are mostly special cases that are handled in GnuCash in a specific way, like return of capital and capital gains.
For example,
```
Error: Transaction does not balance
While parsing file "/cygdrive/d/temp/ledger.dat", line 8192:
While balancing transaction from "/cygdrive/d/temp/ledger.dat", lines 8188-8192:
> 2017/04/12 * return of capital
>       Assets:Investments:ANZ Share Investing:ANZ Cash     647.68 AUD
>       Trading:ASX:IPE                              0.0000 IPE @@ 647.68 AUD
>       Assets:Investments:ANZ Share Investing:Shares:IPE     0.0000 IPE @@ 647.68 AUD
>       Trading:CURRENCY:AUD                        -647.68 AUD
Unbalanced remainder is:
         1295.36 AUD
Amount to balance against:
          647.68 AUD
```
However, as can be seen in GnuCash register, the above amounts are incorrect:
![image](https://user-images.githubusercontent.com/462445/35991378-53e3f656-0d07-11e8-90a7-2587d99c19ed.png)

The transaction should balance according to GnuCash but, once exported, there are three positive values and only one negative, resulting in an unbalanced transaction.

Indeed, in the database the values are also correct:
![image](https://user-images.githubusercontent.com/462445/35991534-c7c01d0c-0d07-11e8-9d0d-9a8bbf04dedb.png)

**Comment by sdementen** [comment]
according to your knowledge of ledger-cli, is there some possible solution ? if not should this ticket be closed ?

**Comment by MisterY** [comment]
Ah, yes. Unfortunately, this prompted me to pause my ledger activities and extract my Asset Allocation implementation into a separate project. I think this is not difficult and it will be more practical (for me) to have it as a cli app.
I tried changing the sign but the real problem is that ledger does not accept negative amount with 0-quantity investment transactions, which would make the above transaction balance.
Let's close for now and revisit should we come back to this topic.
