### ISSUE TITLE
Ability to retrieve balance of placeholder account

### ISSUE THREAD

**Issue by isaacsando** [sdementen/piecash#73]
First off, I love this project. My main use case is reporting and it's an awesome alternative to the built-in GnuCash reports and Python bindings.

I'm mainly pulling accounts and then using get_balance() on each one. I've noticed if I use get_balance() on a placeholder account that 0 is returned. I would expect to get the balance that is shown in GnuCash for that placeholder account. I think it would be nice to be able to use get_balance() on a placeholder account instead of having to write code to loop through the child accounts and doing a sum on them.

**Comment by sdementen** [comment]
Yes indeed, it would be useful!
Maybe worth to add some parameter recurse to get_balance like 
get_balance(recurse=False) => return the balance of the account without its children accounts
get_balance(recurse=True) => return the balance of the account including all of its children accounts

**Comment by sdementen** [comment]
I have pushed a fix in master

**Comment by isaacsando** [comment]
Awesome, thank you! Tried this out and it works. Can I ask another request? Can you make the default for placeholder accounts to recurse? I changed line 267 as follows and it achieves what I'm looking for:
```python
if recurse:
```
to
```python
if recurse or self.placeholder:
```

This does the best of both worlds, returning a balance for placeholder accounts by default and allowing parent accounts not marked as placeholder accounts to sum the children.

**Comment by sdementen** [comment]
I wonder if the semantic is not too unusual this way. For a placeholder, it will return the balance of its direct children accounts that are not placeholders...
Maybe better to have recurse=True the default (as in gnucash)?

**Comment by sdementen** [comment]
I have released version 0.15.0 (http://piecash.readthedocs.io/en/latest/news.html#version-0-15-0-2018-02-21) that default to recurse=True and handles commodity/currency conversion in get_balance.

btw, you can join https://gitter.im/sdementen/piecash if you want to discuss piecash in a gitter chat room

**Comment by isaacsando** [comment]
Thank you!

**Comment by chrisbrasington** [comment]
@sdementen @isaacsando Thank you both, I'm already using this!

**Comment by sdementen** [comment]
Nice! I am wondering if the reconcile status should also be used in the get_balance... Like returning a tuple of "balance, balance of reconciled transactions, etc"
I am not using much the reconciliation feature so I am not that sur  about this.
Btw, have you tried using g gitter for such chat ?
