### ISSUE TITLE
Incorrect assertion will never be true

### ISSUE THREAD

**Issue by jchonig** [sdementen/piecash#76]
File "/usr/local/lib/python2.7/dist-packages/piecash/core/transaction.py", line 230, in __init__
    and not isinstance(post_date, datetime.datetime)), "post_date should be a date object"
```

225                      ):
226  
227             assert enter_date is None or isinstance(enter_date, datetime.datetime), "enter_date should be a datetime object"
228             assert post_date is None or (
229                     isinstance(post_date, datetime.date)
230  ->                 and not isinstance(post_date, datetime.datetime)), "post_date should be a date object"
231  
232             self.currency = currency
233             self.description = description
234             self.enter_date = (enter_date
235                                if enter_date
(Pdb) isinstance(post_date, datetime.datetime)
True
(Pdb) isinstance(post_date, datetime.date)
True
(Pdb) isinstance(post_date, datetime.date) and not isinstance(post_date, datetime.datetime)
False

```
piecash 0.15.0

**Comment by sdementen** [comment]
in 0.15.0, the post_date has been changed to a date object as gnucash encodes the post_date in a specific format, the "neutral time", adding a time component equals to 10:59:00 UTC. Passing a post_date as datetime could violate this requirement

**Comment by jchonig** [comment]
Look at the debugging output.  As the objects inherit your assertion will always fail.

**Comment by sdementen** [comment]
I have the following test
```
from datetime import date,datetime
a=date(2018,2,21)
isinstance(a, date) and not isinstance(a, datetime)
Out[4]: True
a=datetime(2018,2,21)
isinstance(a, date) and not isinstance(a, datetime)
Out[6]: False
```
So it does not fail when it is a `date`. Or I do not understand well your comment.

**Comment by jchonig** [comment]
I see the issue.  I'm confusing error messages because enter-date must be a datetime.datetime and post-date must be a datetime.date.

Sorry for the confusion and thanks for the quick response!

**Comment by sdementen** [comment]
no problem, I forget to mention this backward incompatible change in the changelog
