### ISSUE TITLE
Can not find timezone configuration

### ISSUE THREAD

**Issue by MisterY** [sdementen/piecash#80]
When running in Termux (console environment on Android), piecash throws
`Can not find any timezone configuration` in sa_extra.py, line 81.

I have not looked yet at the code but is there another way to get to the same result?

**Comment by MisterY** [comment]
Blocks https://github.com/MisterY/asset-allocation/issues/22

**Comment by sdementen** [comment]
you must do a 
export TZ=$(getprop persist.sys.timezone)
(or export TZ=CET or whatever tz you are in)

**Comment by sdementen** [comment]
I have just installed termux and it was quite easy to install piecash on a virtualenv in termux.

**Comment by MisterY** [comment]
can I put that somewhere to execute every time? .bashrc or something like that.

**Comment by sdementen** [comment]
I put it in the .bash_profile with also
export SHELL=$(which bash)
for pipenv to work correctly (after having done a "pip install pipenv" in termux)

**Comment by MisterY** [comment]
Fantastic, thanks!
Let me add here that Volume Down on a device is Ctrl in Termux. Useful if you're using nano editor. ;)
