### ISSUE TITLE
ledger export: only one space if account name is very long

### ISSUE THREAD

**Issue by kcwu** [sdementen/piecash#86]
In ledger, account name and amount are separated by at least two spaces. However, if the account name is too long, piecash only use one space character to separate them.

**Comment by sdementen** [comment]
Could you try adding a blank at the end of the strings of line 30 and 32 of core/ledger.py?
To get the following
 ```
            s.append("\t* {:38}   ".format(split.account.fullname))
        else:
            s.append("\t{:40}   ".format(split.account.fullname))
```

**Comment by kcwu** [comment]
Yes, it works after adding one more space there.

**Comment by sdementen** [comment]
If I understand properly, we need to have two blanks between account name and amount. Could you confirm? If so I will make the fix in the repo

**Comment by kcwu** [comment]
Yes, according to
https://www.ledger-cli.org/3.0/doc/ledger3.html#The-Most-Basic-Entry

```
There must be at least two spaces, or a tab, between the amount and the account.
```
