### ISSUE TITLE
GNUCash 3.0 Support

### ISSUE THREAD

**Issue by NigelCleland** [sdementen/piecash#88]
Just an issue to get started on tracking how this is going.

I'll start with adding a new version to here and see what I can get working with the test suite.
If you have any pointer that would be great. Otherwise I'll try and work my way through it and hopefully get a PR done.

```
version_supported = {
    '2.6': {
        'Gnucash': 2060400,
        'Gnucash-Resave': 19920,
        'accounts': 1,
        'billterms': 2,
        'books': 1,
        'budget_amounts': 1,
        'budgets': 1,
        'commodities': 1,
        'customers': 2,
        'employees': 2,
        'entries': 3,
        'invoices': 3,
        'jobs': 1,
        'lots': 2,
        'orders': 1,
        'prices': 2,
        'recurrences': 2,
        'schedxactions': 1,
        'slots': 3,
        'splits': 4,
        'taxtable_entries': 3,
        'taxtables': 2,
        'transactions': 3,
        'vendors': 1,
    },
    '2.7': {
        'Gnucash': 2070200,
        'Gnucash-Resave': 19920,
        'accounts': 1,
        'billterms': 2,
        'books': 1,
        'budget_amounts': 1,
        'budgets': 1,
        'commodities': 1,
        'customers': 2,
        'employees': 2,
        'entries': 4,
        'invoices': 4,
        'jobs': 1,
        'lots': 2,
        'orders': 1,
        'prices': 3,
        'recurrences': 2,
        'schedxactions': 1,
        'slots': 4,
        'splits': 4,
        'taxtable_entries': 3,
        'taxtables': 2,
        'transactions': 4,
        'vendors': 1,
    }
}

```

**Comment by sdementen** [comment]
I was wondering on how to support 3.x and came to a first conclusion that it could be easier to leave the 0.n serie of piecash as 2.6 compatible and start a 1.0 serie that would be 3.0 compatible only.
Supporting multiple versions of gnucash with different sql schemas is complex on the sqlalchemy front...
What do you think?
The 1.n piceash could also drop support for python 2.7 and 3.4

**Comment by NigelCleland** [comment]
I think that might be a smart idea.

The alternative would be to have some form of compatability shim on top of things, detecting which version of GNUCash a workbook is in and then going down the correct code pathway accordingly. 

This is a little bit of a nightmare though as *every* code path would essentially need to have two methods attached with it.

I have a bit of time over the next few weeks. I'll have a better read through the piecash code and see if I can identify an *elegant* way to maintain in a single code base. Do you have a link to the GNUCash 3.0 schema? I've been able to find [this](https://wiki.gnucash.org/wiki/SQL) but I'm not sure if it applies for 3.0.

I'm all in favour of dropping earlier versions, Major target of the project is personal users I'm assuming who should have more control of their working environment as compared to enterprise users stuck on LTS packages.

**Comment by sdementen** [comment]
For sql schema, the one based on piecash is for me the most readable http://piecash.readthedocs.io/en/master/object_model.html

A good approach I did recently to check 2.6.19 was to create an empty book in gnucash and save it to sql. The same in piecash and then I did a sql dump of both and compared both versions with a diff tool. I have fixed already some differences in a local branch that i still need to push.
We could do the same for 3.x to identify clearly the differences. I  think there no much fundamental changes (datetime in SQLite, some slots conventions, increase of digits for commodities) but as some are schema changes, I haven't found yet a way to support this dynamically in sqlalchemy.  

Btw, I have started using "git flow" on my side to manage the different branches.

**Comment by NigelCleland** [comment]
Noted. I'll branch off. Currently reading through reference material in between the day job.

**Comment by sdementen** [comment]
Ok, if you want to ask questions regarding piecash in its structure or approach, fill free.
We also have a gitter chat room if you know the platform

**Comment by gorf** [comment]
Can I use this current dev version? Is there any milestone about the gnucash support? Thank you.

**Comment by sdementen** [comment]
hello @gorf , not yet a milestone. 
In fact, reading the gnucash mailing list, I have the impression gnucash 3.x has still quite some bugs, including SQL specific ones.
How is your gnucash 3 experience ? what backend do you use ? on which OS ?

**Comment by rerobins** [comment]
FYI, this code base is working for me (now that I updated to python 3).  

Gnucash 3 is working fine for me, except some UI issues (fractions for prices instead of decimals).  I'm using MySQL backend on Fedora 28.

**Comment by rerobins** [comment]
3.0 for sure. Just installed 3.1, so need to test that.

Runs as in:
- fetch accounts from book
- read transactions and splits from accounts
- create price objects and save them

I don't modify the book besides price objects, and I do t use any of the scripts associated with piecash. I also don't use pandas.

**Comment by rerobins** [comment]
3.1 as well.

**Comment by rerobins** [comment]
With regards to your list, the first two sound good.  The third seems like expanding your scope too much.  Piecash is really good at accessing data. Reporting sounds like it should be another application or library.  Just my two cents.  

I am a bit biased, since I'm using your library to fetch the data for my reports library/application.

**Comment by sdementen** [comment]
For the third, it should be as simple as adding a .py file in gnucash user folder, a file with a function that takes a book in input and returns whatever it wants (HTML, xls,...). The report would then appear in gnucash report menu and would run as other reports.



Sent from my Samsung Galaxy smartphone.
ENGIE Mail Disclaimer: http://www.engie.com/disclaimer/

**Comment by gorf** [comment]
Thank you. Gnucash 3.1 seems good, and I have used it at work.  The sqlite and xml  backend worked fine. I use it at win 10 and gentoo linux. There are some wrong at Chinese input at win 10. 
How can  I use the dev version?

**Comment by sdementen** [comment]
@gorf , on GitHub, you select the branch feature/py3-gnucash3 and then download the source code as zip file, you decompress it somewhere on your drive, go into this directory and run "python setup install"

**Comment by rerobins** [comment]
Can also:

pip install git+https://github.com/sdementen/piecash.git@feature/py3-gnucash3

**Comment by sdementen** [comment]
Even better! This should be added to the docs!

**Comment by gorf** [comment]
Thank you for your patience.  I use it successfully. 
The command should be  "python setup.py install"

**Comment by FelixSchwarz** [comment]
I ported my old gnucash-based code to piecash (just reading some entries) and everything worked fine with Python 2.7 / GnuCash 3.2 / piecash git (master). So at least some basic functionality is already there.

**Comment by MisterY** [comment]
@NigelCleland, post_date is declared as date and enter_date as datetime in transaction.py:
```
    _post_date = Column('post_date', _DateAsDateTime(neutral_time=True), index=True)
    enter_date = Column('enter_date', _DateTime)
```

**Comment by MisterY** [comment]
Same issue but for the second date type:
https://github.com/sdementen/piecash/pull/102

**Comment by MisterY** [comment]
Any update on this? Currently the code is only available on GitHub but not on PyPi, making it difficult to deploy to Termux, for example.
Would you like to create a separate distribution (and repo) for v3 support, if people still need v2 active?

**Comment by sdementen** [comment]
I wanted first to migrate cleanly the test suite (i.e. saving the gnucash
books in a 3.0 version and run the tests on them).
But I could release already a piecash for python 3.0 before this (to avoid
the problems you are experiencing).
I prefer to do it on the same repo.
I will do it the next weekend (now, I am without my computer for the week).

**Comment by MisterY** [comment]
Great, thanks! I'm currently looking at PySimpleGUI and Remi. Could finally get the same GUI running on Android and PC for Python apps.

**Comment by sdementen** [comment]
If your app needs some charts and can be web based, there is also https://plot.ly/products/dash/ that can be used as pure python web UI

**Comment by MisterY** [comment]
Thanks, @sdementen. I've tried a few frameworks that do the similar thing but I'm no longer sure that a framework that translates Python into HTML is a good idea. I'm now leaning more to do HTML as HTML and Python as Python, so perhaps I go back to the concept of a single-page application which uses Python web API in Flask, or something like that.
There are no unnecessary extra elements in that approach although even then it can get fairly complex quickly.

**Comment by sdementen** [comment]
The 1.0.0 closes this issue
