### ISSUE TITLE
account.get_balance returns wrong amount

### ISSUE THREAD

**Issue by lamarc5** [sdementen/piecash#89]
With accounts having mixed type childs, account.get_balance will add all child balances as positive values, irrespective of child type. IE ASSETS amounts will be added to LIABILITIES, giving incorrect result. 
get_balance should return the value signed relative to the parent type.
Attached a suggested correction
[get_balance.py.txt](https://github.com/sdementen/piecash/files/1976543/get_balance.py.txt)

piecash 0.18.0, python 3.6.5 on ubuntu 18.04

**Comment by sdementen** [comment]
Good point!
Would you have an example book with mixed type account so I can add it in the test suite ? It will also helps me understand the issue.

**Comment by sdementen** [comment]
Any sample book with expected results from the get_balance?

**Comment by sdementen** [comment]
fixed in piecash 1.1
