### ISSUE TITLE
Add requests to install_requires

### ISSUE THREAD

**Issue by williamjacksn** [sdementen/piecash#90]
The current version of `piecash` (0.18.0) requires `requests` but that package is not listed in `install_requires` so it is not installed automatically.

    > pip install piecash
    Collecting piecash
      Downloading https://files.pythonhosted.org/packages/1b/4e/c14f5502f1f8d758f0c6b4c3020dac1ae3133e0970e990d2e572726bb1de/piecash-0.18.0.tar.gz (4.0MB)
        100% |████████████████████████████████| 4.0MB 319kB/s
    Collecting SQLAlchemy>=1.0 (from piecash)
      Downloading https://files.pythonhosted.org/packages/c1/c8/392fcd2d01534bc871c65cb964e0b39d59feb777e51649e6eaf00f6377b5/SQLAlchemy-1.2.7.tar.gz (5.6MB)
        100% |████████████████████████████████| 5.6MB 237kB/s
    Collecting SQLAlchemy-Utils>=0.31 (from piecash)
      Downloading https://files.pythonhosted.org/packages/28/17/fedf5a8b2492a7d12986273b7d661419970b1866f3be3f897114aa3c7195/SQLAlchemy-Utils-0.33.3.tar.gz (126kB)
        100% |████████████████████████████████| 133kB 370kB/s
    Collecting pytz (from piecash)
      Downloading https://files.pythonhosted.org/packages/dc/83/15f7833b70d3e067ca91467ca245bae0f6fe56ddc7451aa0dc5606b120f2/pytz-2018.4-py2.py3-none-any.whl (510kB)
        100% |████████████████████████████████| 512kB 1.6MB/s
    Collecting tzlocal (from piecash)
      Downloading https://files.pythonhosted.org/packages/cb/89/e3687d3ed99bc882793f82634e9824e62499fdfdc4b1ae39e211c5b05017/tzlocal-1.5.1.tar.gz
    Collecting click (from piecash)
      Downloading https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl (71kB)
        100% |████████████████████████████████| 71kB 2.6MB/s
    Collecting six (from SQLAlchemy-Utils>=0.31->piecash)
      Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
    Installing collected packages: SQLAlchemy, six, SQLAlchemy-Utils, pytz, tzlocal, click, piecash
      Running setup.py install for SQLAlchemy ... done
      Running setup.py install for SQLAlchemy-Utils ... done
      Running setup.py install for tzlocal ... done
      Running setup.py install for piecash ... done
    Successfully installed SQLAlchemy-1.2.7 SQLAlchemy-Utils-0.33.3 click-6.7 piecash-0.18.0 pytz-2018.4 six-1.11.0 tzlocal-1.5.1
    
    > python -c 'import piecash'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/william/.pyenv/versions/piecash/lib/python3.6/site-packages/piecash/__init__.py", line 15, in <module>
        from .core import (
      File "/home/william/.pyenv/versions/piecash/lib/python3.6/site-packages/piecash/core/__init__.py", line 1, in <module>
        from .session import create_book, open_book, Version
      File "/home/william/.pyenv/versions/piecash/lib/python3.6/site-packages/piecash/core/session.py", line 11, in <module>
        from piecash.core import factories
      File "/home/william/.pyenv/versions/piecash/lib/python3.6/site-packages/piecash/core/factories.py", line 5, in <module>
        from ..yahoo_client import get_latest_quote
      File "/home/william/.pyenv/versions/piecash/lib/python3.6/site-packages/piecash/yahoo_client.py", line 15, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'

**Comment by sdementen** [comment]
I will fix this by removing the yahoo functionality as it is anyway broken

**Comment by sdementen** [comment]
fixed in 0.19.0

**Comment by williamjacksn** [comment]
I am experiencing this problem again in version 1.1.1.

**Comment by sdementen** [comment]
Sorry, I'll have a look and fix this (more permanently)

**Comment by sdementen** [comment]
1.1.2 fixes this
