### ISSUE TITLE
Adding Project onto "Projects per language" 

### ISSUE THREAD

**Issue by u2berggeist** [sdementen/piecash#94]
I was hoping to add my project, [csv2cash](https://github.com/u2berggeist/csv2cash) onto the [Projects per language](http://piecash.readthedocs.io/en/master/doc/github_links.html) page on ReadTheDocs, but noticed that it was actually "auto" generated from a GitHub search.

Should I do a PR with just my project added, or does the list just need to be re-generated?

**Comment by sdementen** [comment]
You're welcome to add it manually till the next update 
Next time I run the update, it'll be replaced

**Comment by u2berggeist** [comment]
Cool! I've created PR #95 .
