### ISSUE TITLE
Access to Additional Account Fields [Notes / Others]

### ISSUE THREAD

**Issue by torchtarget** [sdementen/piecash#96]
Hi, 
Firstly thanks for the great tool it really does make interacting with my gnucash files so much easier. 
I am writing a simple saltedge (Decent bank aggregator API) importer and would prefer to be able to embed the mapping table from saltedge within the gnucash file itself, to not have to create a separate mapping file.  
It would be great to store the saltedge account and category ID within the Account notes field (now I am using the description field, but that is not as tidy).  Maybe there is somewhere else to store it? 
Would also be excellent to be able to store certain metadata in the notes field of the account such as latest refresh etc.....

**Comment by sdementen** [comment]
Hello Christian, there are a lot of places where you can store data in gnucash. One of them is the slots and you can create your own slots. However they will not be visible in the gnucash UI.
For example the Bayed classifier is using slots to store its mapping.
Maybe that the gnucash mailing list is a better place to ask your use case (where to store extra info needed by an external script, be it written with the official python bindings or piecash)

**Comment by sdementen** [comment]
I close the issue as it is inactive for 2y
